"""create capture sessions table

Revision ID: 3cc398b093fc
Revises:
Create Date: 2026-07-27 18:18:56.349005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc398b093fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packet_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'stopped', 'failed')", name='ck_capture_sessions_status'),
    sa.CheckConstraint('packet_count >= 0', name='ck_capture_sessions_packet_count_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capture_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capture_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_sessions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capture_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capture_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_capture_sessions_started_at'))

    op.drop_table('capture_sessions')
    # ### end Alembic commands ###
